### ISSUE TITLE
Wow ... You did it

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#22]
Hi
First... What a TUNE UP this is! You lads are doing a fantastic job! I am impressed. The new functions, style and design is AMAZING!!! - This is setting the bar so high!! I salute you!!

I do only have small issues - to report - But it WORKS!!!

1: After I have captured a payment I get a RED Warning "Can't set header" or something like: Header already set"
Then I check on epay.dk  login to my back end and see the capture is done (also shows perfectly in the plugin). 

2: Then I set the order to "Completed" and "Save" ... Then I get an error: ""  <<< Just two citation marks: "" ?? (Red error again)
Then I click my "Shipment" label button and generate a label to print! - Done
Except for the warnings ... Everything works like a champ.

My site: https://herbalcenter.dk 
and http://bizdoktor.dk

have a great day and thanks for all your effort and hard work!! it is appriciated!!

Peter

**Comment by AllanWLie** [comment]
@Netzie Thank you for your kind words :)

**Regarding your issue:**
We have been experiencing some latency issues since Black Friday, and we have seen an error similar to what you describe "Error fetching http headers" This error is because of the latency is greater than the allowed SOAP timeout defined in your php.ini. This error should go away over time, since we are working hard to reduce the latency.


If the error persists, please write to our support at support@bambora.com

Again thank you.

**Kind regards**
Allan
