### ISSUE TITLE
Fatal error with subscribtion

### ISSUE THREAD

**Issue by Netzie** [ePay/woocommerce#25]
Hi Lads,

First...Thanks a million for your excellent work. This new facelift and many bugs fix has made a huge difference! 

A small thing:

When a subscribtion ordre fails - this happends? When I try to delete the order?

Fatal error: Uncaught exception 'Exception' with message 'Bambora abonnements id blev ikke fundet' in xxxx/public_html/wp-content/plugins/woocommerce-gateway-epay-dk/woocommerce-gateway-epay-dk.php:548 Stack trace: #0 [internal function]: WC_Gateway_EPayDk->subscription_cancellation(Object(WC_Subscription)) #1 xxx/public_html/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #2 xxx/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #3 xxx/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 xxx/public_html/wp-content/plugins/woocommerce-subscriptions/includes/gateways/class-wc-subscriptions-payment-gateways.php(164): do_action('woocommerce_sub...', Object(WC_Subscription)) #5 [internal function]: WC_Subscriptions_Payment_Gateways::trigger_gateway_status_updated_hook(Object(WC_Subscription), 'cancelled') #6 xxx/public_html/wp-includes/class-wp-hook.php(300): call_user_func_array('WC_Subscrip in xxx/public_html/wp-content/plugins/woocommerce-gateway-epay-dk/woocommerce-gateway-epay-dk.php on line 548

Best regards

Peter
http://Bizdoktor.dk

**Comment by AllanWLie** [comment]
Hi @Netzie 

Thank you for your kind words and thank you for reporting this bug.

We have corrected the bug in our code, but we will not make a new release right now, since we are working on adding logging to the module.

For now the solution to this bug is to remove this line (throw $ex;):
https://github.com/ePay/woocommerce/blob/master/woocommerce-gateway-epay-dk/woocommerce-gateway-epay-dk.php#L574

Have a nice day

Kind regards
Allan

**Comment by AllanWLie** [comment]
@Netzie 
The error have been fixed in the latest release: https://github.com/ePay/woocommerce/releases/latest
